<footer>
        <div class="footer">
            <p class="center">&copy; 2024 Microself Corp.</p>
            <p class="center">Email:&nbsp;<a href="mailto:microselfcompany@gmail.com">microselfcompany@gmail.com</a></p>
            <p class="center">Phone number: (+84)916785072</p>
            <p class="center">Address: A35 Bach Dang St., Ward 2, Tan Binh Discrict, Ho Chi Minh City, Vietnam</p>
        </div>
</footer>