<header>
        <div class="navbar">
            <div class="logo">
                <a href="./index.php">Microself</a>
            </div>
            <div class="menu">
                <a href="./index.php">Home</a>
                <a href="./jobs.php">Career</a>
                <a href="./apply.php">Apply</a>
                <a href="./about.php">About</a>
                <a href="./login.php">Log In</a>
            </div>
        </div>
</header>